title = "Rohaan's Blog"
languageCode = "en-us"
baseURL = "https://r0haaaan.github.io/"
theme = "leaveit" 
disqusShortname = "your disqus shortname"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
  since = 2020
  author = "रोहन कुमार"
  avatar = "static/images/reg.png"
  description = "Rohan Kumar's tech blog"

[params.social]
  Github = "rohanKanojia"
  Twitter = "r0hankanojia"
  LinkedIn = "rohan-kumar-39356a84/"
  Medium = "@rohaan"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  InstagramID = "your instagram"
  Name = "Rohan Kumar"
  HeaderUsername = "Rohan Kumar"
  HeaderHostname = "Rohan Kumar"
  Email = "rohankanojia420@gmail.com"
  About = "I am a Software Engineer currently living in Chandigarh, India. My interests range from programming to cycling. I am also interested in movies. These days I am working in Red Hat to improve the experience of Java developers on top of Kubernetes. If you are a Java developer trying to move projects to Kubernetes / Red Hat OpenShift. You may find my projects useful. You can find most of my work on my Github profile. You can click the button above to checkout my blogs on Medium."
  ProfilePicture = "images/reg.png"
  GoogleAnalytics = "your_google_analytics_id"
